'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';
import { Box, Flex } from '@chakra-ui/react';

import { useState } from 'react';
import { Providers } from '@/src/provider';
import Sidebar from '@/src/utils/Sidebar';
import Header from '@/src/utils/Header';
import Footer from '@/src/utils/Footer';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const noNav =
    pathname?.startsWith('/login') || pathname?.startsWith('register');
  const [showSide, setShowSide] = useState<boolean>(false);
  console.log({ showSide });
  return (
    <html lang="en">
      <body>
        <Providers>
          {noNav ? (
            <Box>{children}</Box>
          ) : (
            <Box>
              <Header showSide={showSide} setShowSide={setShowSide} />
              <Sidebar showSide={showSide} setShowSide={setShowSide} />
              <Box as="main" minH={'90vh'}>
                {children}
              </Box>
              <Footer />
            </Box>
          )}
        </Providers>
      </body>
    </html>
  );
}
